#pragma once

#include "WString.h"

const char *rootCACertificate_IPAPI =
"-----BEGIN CERTIFICATE-----\r\n"\
"MIIDfDCCAwOgAwIBAgISA87WGCXW1JXDfa6QZStUqUD4MAoGCCqGSM49BAMDMDIx\r\n"\
"CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF\r\n"\
"MTAeFw0yNDAzMDkxNzI5MDlaFw0yNDA2MDcxNzI5MDhaMBMxETAPBgNVBAMTCGlw\r\n"\
"YXBpLmNvMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC0nAPTO/8avQfKtR3GPE\r\n"\
"wZlBGeJ3VbDnsgpT4sAsXMDEnjxCIQFSj3NzS4+JuvsrGGBZVjemMTj8Grkx5SGO\r\n"\
"5qOCAhYwggISMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI\r\n"\
"KwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUbDUdnSiLzYeIlD29Fmq2\r\n"\
"du4iMUEwHwYDVR0jBBgwFoAUWvPtK/w2wjd5uVIw6lRvz1XLLqwwVQYIKwYBBQUH\r\n"\
"AQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vZTEuby5sZW5jci5vcmcwIgYIKwYB\r\n"\
"BQUHMAKGFmh0dHA6Ly9lMS5pLmxlbmNyLm9yZy8wHwYDVR0RBBgwFoIKKi5pcGFw\r\n"\
"aS5jb4IIaXBhcGkuY28wEwYDVR0gBAwwCjAIBgZngQwBAgEwggEEBgorBgEEAdZ5\r\n"\
"AgQCBIH1BIHyAPAAdgBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiEcwAA\r\n"\
"AY4kedmnAAAEAwBHMEUCIQDY6/YSDphvmeOXj3GllOS/+axPEuBBAD55HYTsouNt\r\n"\
"ggIgFvRLEbyEmWCFWCE6y4HD0txZpeRPFUCR/Axxrrto9ZYAdgB2/4g/Crb7lVHC\r\n"\
"Ycz1h7o0tKTNuyncaEIKn+ZnTFo6dAAAAY4kedn6AAAEAwBHMEUCIQC2x9N4jV1/\r\n"\
"BGj1g126dF8WFYWOL7lmGNGiDWL1TyqaxwIgJKINoyOmITtGPK0oRHVXxFAsFQZt\r\n"\
"9mRSNdlUJfJDZmIwCgYIKoZIzj0EAwMDZwAwZAIwVT/Uqra+xhTsVcFizlEIDGPq\r\n"\
"24ayZ7pgkF4Cm5uBo3VDRzkJuZjeSNnCBa/ihgZJAjBjlR1fPmB0yJJQfUI8krPM\r\n"\
"I22JCz7Jrdw0Ynm+RU4XoVRtPzAUKA5UFNCrXZJFNJ0=\r\n"\
"-----END CERTIFICATE-----\r\n";


const char *rootCA_ISRG_ROOT_X2 =
"-----BEGIN CERTIFICATE-----\r\n"\
"MIICGzCCAaGgAwIBAgIQQdKd0XLq7qeAwSxs6S+HUjAKBggqhkjOPQQDAzBPMQsw\r\n"\
"CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg\r\n"\
"R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yMDA5MDQwMDAwMDBaFw00\r\n"\
"MDA5MTcxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5ldCBT\r\n"\
"ZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgyMHYw\r\n"\
"EAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0HttwW\r\n"\
"+1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7AlF9\r\n"\
"ItgKbppbd9/w+kHsOdx1ymgHDB/qo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0T\r\n"\
"AQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEKWrt5LSDv6kviejM9ti6lyN5UwCgYIKoZI\r\n"\
"zj0EAwMDaAAwZQIwe3lORlCEwkSHRhtFcP9Ymd70/aTSVaYgLXTWNLxBo1BfASdW\r\n"\
"tL4ndQavEi51mI38AjEAi/V3bNTIZargCyzuFJ0nN6T5U6VR5CmD1/iQMVtCnwr1\r\n"\
"/q4AaOeMSQ+2b1tbFfLn\r\n"\
"-----END CERTIFICATE-----\r\n";